In [1]:
import numpy as np

In [6]:
print(np.cos(np.pi))
print(np.sqrt(4))
print(np.log2(2^5))

-1.0
2.0
2.807354922057604


In [30]:
vec=np.array([1,2,3])
print(vec)
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print(mat.T)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
vec2=np.arange(0,15)
print(vec2)
vec3=np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  9 15]


In [19]:
vec4=np.linspace(0,5,10)
print(vec4)
vec5= vec4.reshape(5,2)
print(vec5)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [23]:
mat2=np.zeros([5,3])
print(mat2)
mat3=np.ones([3,5])
print(mat3)
mat4=np.eye(5)
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
vec5=np.arange(1,6)
vec6=np.arange(3,8)
print(vec5+vec6)
print(vec5-vec6)
print(vec5*vec6)
print(np.sqrt(vec5))

[ 4  6  8 10 12]
[-2 -2 -2 -2 -2]
[ 3  8 15 24 35]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [42]:
print(mat)
print(vec)
product=np.matmul(mat,vec)
print(product)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[14 32 50]


In [43]:
print(np.linalg.solve(mat,product))
print(np.linalg.inv(mat))

[-0.8  5.6  1.2]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [44]:
vec7=np.array([-0.8,5.6,1.2])
print(np.matmul(mat,vec7))

[14. 32. 50.]


In [52]:
vec8=np.array([6,'blue','red','orange','purple','purple','orange','red'])
print(vec8)
print(np.unique(vec8))

['6' 'blue' 'red' 'orange' 'purple' 'purple' 'orange' 'red']
['6' 'blue' 'orange' 'purple' 'red']


In [68]:
rand_mat=np.random.rand(5,5)
print(rand_mat)
rand_mat2=np.random.randn(10,5)
print(rand_mat2)

[[0.86333659 0.74978837 0.09614825 0.66195494 0.10516455]
 [0.60419974 0.3176832  0.48297625 0.59382585 0.59099605]
 [0.1207531  0.65642746 0.89979448 0.8688769  0.27412039]
 [0.01071822 0.00590807 0.7729457  0.11163334 0.8840309 ]
 [0.10276207 0.5298085  0.3416711  0.12306624 0.11134815]]
[[-0.32500459  0.06658804  1.68250086  1.05824281  0.63640026]
 [ 1.65601563 -0.72067592  0.78554087 -0.71176497 -1.19900435]
 [ 1.39632693  0.47567229  0.28771661  0.17387139 -2.13781069]
 [-0.00665612  1.19069766 -0.24375117  0.32646463 -0.40530955]
 [-0.95511953 -0.13759716 -0.94137925  0.94705321 -0.96088929]
 [-0.30384973  1.63628661 -1.67297908  0.85370024 -0.76399409]
 [ 0.06550445 -0.4587955   0.73575462 -2.61943138 -0.15653993]
 [-1.01039869  0.58526592  1.12841823 -0.82216281 -0.04122669]
 [-0.37769269 -0.32252001  0.81490562 -0.81985752 -1.12666372]
 [-0.77127652  1.1572269  -0.98438519  0.10628464 -1.37879179]]


In [69]:
print(np.mean(rand_mat))
print(np.std(rand_mat))

0.4351975355336837
0.3062387999629552


In [70]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.005908065613693614
1.6825008568331972


In [72]:
rand_vec=np.random.randn(19)
print(rand_vec)

[-0.03921708 -0.30433427 -0.0307015   0.95807621 -0.37254393 -0.21246935
 -0.00888251  0.45120887  0.26310134 -0.47255714 -0.77637481  0.47231955
  0.58523118 -0.43201398  1.11009826 -1.26162033  0.05264155 -0.23423574
 -1.01902612]


In [73]:
print(rand_vec[6])

-0.008882510076446224


In [74]:
print(rand_vec[4:9])

[-0.37254393 -0.21246935 -0.00888251  0.45120887  0.26310134]


In [76]:
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-0.03921708  0.95807621 -0.00888251 -0.47255714  0.58523118]


In [78]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.86333659 0.74978837 0.09614825 0.66195494 0.10516455]
 [0.60419974 0.3176832  0.48297625 0.59382585 0.59099605]
 [0.1207531  0.65642746 0.89979448 0.8688769  0.27412039]
 [0.01071822 0.00590807 0.7729457  0.11163334 0.8840309 ]
 [0.10276207 0.5298085  0.3416711  0.12306624 0.11134815]]
0.4829762506140999
0.4829762506140999


In [79]:
print(rand_mat[0:2,1:3])

[[0.74978837 0.09614825]
 [0.3176832  0.48297625]]


In [87]:
print(rand_vec)
rand_vec[1:4]=5
print(rand_vec)
rand_vec[2:4]=[8,9]
print(rand_vec)

[-0.03921708  5.          5.          5.         -0.37254393 -0.21246935
 -0.00888251  0.45120887  0.26310134 -0.47255714 -0.77637481  0.47231955
  0.58523118 -0.43201398  1.11009826 -1.26162033  0.05264155 -0.23423574
 -1.01902612]
[-0.03921708  5.          5.          5.         -0.37254393 -0.21246935
 -0.00888251  0.45120887  0.26310134 -0.47255714 -0.77637481  0.47231955
  0.58523118 -0.43201398  1.11009826 -1.26162033  0.05264155 -0.23423574
 -1.01902612]
[-3.92170756e-02  5.00000000e+00  8.00000000e+00  9.00000000e+00
 -3.72543925e-01 -2.12469350e-01 -8.88251008e-03  4.51208870e-01
  2.63101340e-01 -4.72557141e-01 -7.76374807e-01  4.72319546e-01
  5.85231180e-01 -4.32013981e-01  1.11009826e+00 -1.26162033e+00
  5.26415543e-02 -2.34235736e-01 -1.01902612e+00]


In [88]:
rand_vec=np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-2.11206423  1.09975064  0.27779429  0.04413951 -0.04980819 -0.74500308
 -0.04637968 -0.52025111  0.61628151  0.26122606  0.47873343  0.4049078
 -1.74350558  0.57092521 -0.83378494]
[False  True  True  True False False False False  True  True  True  True
 False  True False]
[1.09975064 0.27779429 0.04413951 0.61628151 0.26122606 0.47873343
 0.4049078  0.57092521]


In [89]:
np.save("saved_file_name",rand_mat2)

In [90]:
np.savez("zsaved_file_name",rand_mat2=rand_mat2,rand_vec=rand_vec)

In [92]:
loaded_file=np.load("saved_file_name.npy")
loaded_file2=np.load("zsaved_file_name.npz")

In [93]:
print(loaded_file)
print(loaded_file2)

[[-0.32500459  0.06658804  1.68250086  1.05824281  0.63640026]
 [ 1.65601563 -0.72067592  0.78554087 -0.71176497 -1.19900435]
 [ 1.39632693  0.47567229  0.28771661  0.17387139 -2.13781069]
 [-0.00665612  1.19069766 -0.24375117  0.32646463 -0.40530955]
 [-0.95511953 -0.13759716 -0.94137925  0.94705321 -0.96088929]
 [-0.30384973  1.63628661 -1.67297908  0.85370024 -0.76399409]
 [ 0.06550445 -0.4587955   0.73575462 -2.61943138 -0.15653993]
 [-1.01039869  0.58526592  1.12841823 -0.82216281 -0.04122669]
 [-0.37769269 -0.32252001  0.81490562 -0.81985752 -1.12666372]
 [-0.77127652  1.1572269  -0.98438519  0.10628464 -1.37879179]]


In [95]:
print(loaded_file2["rand_vec"])

[-2.11206423  1.09975064  0.27779429  0.04413951 -0.04980819 -0.74500308
 -0.04637968 -0.52025111  0.61628151  0.26122606  0.47873343  0.4049078
 -1.74350558  0.57092521 -0.83378494]


In [99]:
np.savetxt("saved_text_file.txt",rand_mat2,delimiter=',')
rand_mat_txt=np.loadtxt("saved_text_file.txt",delimiter=',')
print(rand_mat_txt)

[[-0.32500459  0.06658804  1.68250086  1.05824281  0.63640026]
 [ 1.65601563 -0.72067592  0.78554087 -0.71176497 -1.19900435]
 [ 1.39632693  0.47567229  0.28771661  0.17387139 -2.13781069]
 [-0.00665612  1.19069766 -0.24375117  0.32646463 -0.40530955]
 [-0.95511953 -0.13759716 -0.94137925  0.94705321 -0.96088929]
 [-0.30384973  1.63628661 -1.67297908  0.85370024 -0.76399409]
 [ 0.06550445 -0.4587955   0.73575462 -2.61943138 -0.15653993]
 [-1.01039869  0.58526592  1.12841823 -0.82216281 -0.04122669]
 [-0.37769269 -0.32252001  0.81490562 -0.81985752 -1.12666372]
 [-0.77127652  1.1572269  -0.98438519  0.10628464 -1.37879179]]
